"""PRD US-003 lines 308-311: property-based scheduler tests.

These tests assert cross-cutting invariants of the scheduler over
randomized ``LockedAction`` sets generated by ``hypothesis``. The first
test (line 308) pins the order-independence guarantee for non-conflicting
actions: ``SerialScheduler`` and ``PriorityScheduler`` must produce
equivalent final engine state when no two actions share a write-lock,
because non-conflicting actions commute under any in-lane execution
order.
"""

from __future__ import annotations

from collections import Counter

from hypothesis import given, settings, strategies as st

from defi_sim.core.types import SwapAction
from defi_sim.engine.scheduler import (
    LockedAction,
    ParallelLane,
    PriorityScheduler,
    SerialScheduler,
    conflicts,
    scheduler_priority_score,
)


def _independent_action(agent_id: str, lock: str, amount: int) -> LockedAction:
    """Build a LockedAction whose only write-lock is ``lock``.

    ``amount`` is folded into ``amount_in`` so the model state below
    accumulates a meaningful (non-trivially-equal) per-lock value
    derived from each action — not just a count.
    """
    return LockedAction(
        action=SwapAction(
            agent_id=agent_id,
            token_in="SOL",
            token_out="USDC",
            amount_in=amount,
        ),
        write_locks=frozenset({lock}),
    )


def _apply_lanes_to_model_state(lanes: list[ParallelLane]) -> dict[str, int]:
    """Execute every action through a commutative model executor.

    The model treats each LockedAction's effect as ``state[lock] +=
    action.amount_in`` for each write-lock the action holds. Within a
    lane, actions execute in lane order; across lanes, the lanes execute
    in their emitted order. Because non-conflicting actions never share
    a write-lock, the per-lock sums collapse to the same Counter
    regardless of how the scheduler partitions or orders them — that's
    the order-independence property under test.
    """
    state: Counter[str] = Counter()
    for lane in lanes:
        for la in lane.actions:
            for lock in la.write_locks:
                state[lock] += la.action.amount_in
    return dict(state)


@settings(max_examples=200, deadline=None)
@given(
    n=st.integers(min_value=0, max_value=20),
    seed=st.integers(min_value=0, max_value=1_000_000),
    permutation_seed=st.integers(min_value=0, max_value=1_000_000),
)
def test_serial_and_parallel_produce_equivalent_state_when_no_conflicts(
    n: int, seed: int, permutation_seed: int
) -> None:
    """PRD US-003 line 308: random action sets where no two actions
    share a write-lock yield the same final engine state through
    ``SerialScheduler`` and ``PriorityScheduler``.

    Each generated LockedAction holds a unique write-lock
    (``acct-{i}``), so the conflict graph is edgeless. The model
    executor in ``_apply_lanes_to_model_state`` is a commutative
    accumulator over (lock, amount_in) pairs. Independence at the lock
    level guarantees the schedulers' lane partitions and inter-lane
    orderings cannot diverge the accumulated state. The randomized
    ``permutation_seed`` shuffles the input order so the test discriminates
    against a buggy SerialScheduler that drops or reorders inputs and
    against a buggy PriorityScheduler that fails to emit one component
    per non-conflicting action.
    """
    import random as _random

    rng = _random.Random(seed)
    locks = [f"acct-{i}" for i in range(n)]
    amounts = [rng.randint(1, 1_000_000) for _ in range(n)]

    actions = [
        _independent_action(agent_id=f"agent-{i}", lock=lock, amount=amount)
        for i, (lock, amount) in enumerate(zip(locks, amounts))
    ]

    perm_rng = _random.Random(permutation_seed)
    perm_rng.shuffle(actions)

    serial_lanes = SerialScheduler().schedule(actions, slot=0)
    priority_lanes = PriorityScheduler().schedule(actions, slot=0)

    serial_state = _apply_lanes_to_model_state(serial_lanes)
    priority_state = _apply_lanes_to_model_state(priority_lanes)

    assert serial_state == priority_state

    # Stronger pin: with N non-conflicting actions, every action lands
    # exactly once under both schedulers. This catches a regression where
    # one scheduler silently drops or duplicates actions while the model
    # accumulator still happens to match.
    assert sum(len(lane.actions) for lane in serial_lanes) == n
    assert sum(len(lane.actions) for lane in priority_lanes) == n


def _scored_action(
    agent_id: str,
    lock: str,
    cu_price: int,
    cu_limit: int,
    num_signatures: int,
) -> LockedAction:
    """Build a LockedAction whose ``scheduler_priority_score`` varies with
    the supplied fee fields.

    The lock is single-write so multiple actions sharing the same ``lock``
    land in the same conflict-graph component (and thus the same
    ``ParallelLane``) — that's how we get multi-action lanes whose internal
    ordering is the property under test.
    """
    action = SwapAction(
        agent_id=agent_id,
        token_in="SOL",
        token_out="USDC",
        amount_in=1,
        num_required_signatures=num_signatures,
        compute_unit_limit=cu_limit,
        compute_unit_price_micro_lamports=cu_price,
    )
    return LockedAction(action=action, write_locks=frozenset({lock}))


@settings(max_examples=200, deadline=None)
@given(
    n=st.integers(min_value=0, max_value=20),
    num_locks=st.integers(min_value=1, max_value=4),
    seed=st.integers(min_value=0, max_value=1_000_000),
    permutation_seed=st.integers(min_value=0, max_value=1_000_000),
)
def test_within_lane_priority_order_preserved(
    n: int, num_locks: int, seed: int, permutation_seed: int
) -> None:
    """PRD US-003 line 309: within each ``ParallelLane`` returned by
    ``PriorityScheduler``, actions are sorted by
    ``scheduler_priority_score(locked_action)`` descending.

    Generates ``n`` actions whose write-locks are sampled from a small
    pool (``num_locks`` distinct locks) so multiple actions cluster into
    the same conflict component — that's how we exercise multi-action
    lanes. Fee fields (``compute_unit_price_micro_lamports``,
    ``compute_unit_limit``, ``num_required_signatures``) are randomized to
    produce a non-degenerate distribution of priority scores. The
    randomized ``permutation_seed`` shuffles input order to defeat a buggy
    scheduler that returns input order rather than score-descending order.
    """
    import random as _random

    rng = _random.Random(seed)
    actions: list[LockedAction] = []
    for i in range(n):
        lock = f"acct-{rng.randrange(num_locks)}"
        cu_price = rng.randint(0, 100_000)
        cu_limit = rng.randint(1, 1_400_000)
        num_sigs = rng.randint(1, 4)
        actions.append(
            _scored_action(
                agent_id=f"agent-{i}",
                lock=lock,
                cu_price=cu_price,
                cu_limit=cu_limit,
                num_signatures=num_sigs,
            )
        )

    perm_rng = _random.Random(permutation_seed)
    perm_rng.shuffle(actions)

    lanes = PriorityScheduler().schedule(actions, slot=0)

    # Discriminator: with multi-action lanes, the within-lane order must
    # be score-descending. Single-action and empty lanes are trivially
    # sorted but included so the assertion holds for every lane.
    for lane in lanes:
        scores = [scheduler_priority_score(la) for la in lane.actions]
        assert scores == sorted(scores, reverse=True), (
            f"lane not sorted by scheduler_priority_score descending: {scores}"
        )

    # Total-action invariant — catches a regression where the scheduler
    # silently drops or duplicates actions while the per-lane sort still
    # passes.
    assert sum(len(lane.actions) for lane in lanes) == n


def _locked_action_with_locks(
    agent_id: str,
    read_locks: frozenset[str],
    write_locks: frozenset[str],
) -> LockedAction:
    """Build a LockedAction with arbitrary read/write lock sets.

    Used to exercise the conflict-graph predicate over the full
    read/write space — including read-read overlaps (non-conflicting),
    write-write overlaps (conflicting), and read-write overlaps
    (conflicting).
    """
    return LockedAction(
        action=SwapAction(
            agent_id=agent_id,
            token_in="SOL",
            token_out="USDC",
            amount_in=1,
        ),
        read_locks=read_locks,
        write_locks=write_locks,
    )


def _external_components(
    actions: list[LockedAction],
) -> list[int]:
    """Compute connected-component ids over the conflict graph by union-find.

    Returns a list ``component[i]`` such that two actions share an id
    iff they belong to the same connected component under ``conflicts``.
    Independent of ``PriorityScheduler``'s implementation — so the test
    can compare scheduler output against this oracle.
    """
    n = len(actions)
    parent = list(range(n))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(x: int, y: int) -> None:
        rx, ry = find(x), find(y)
        if rx != ry:
            parent[rx] = ry

    for i in range(n):
        for j in range(i + 1, n):
            if conflicts(actions[i], actions[j]):
                union(i, j)
    return [find(i) for i in range(n)]


@settings(max_examples=200, deadline=None)
@given(
    n=st.integers(min_value=0, max_value=15),
    num_locks=st.integers(min_value=1, max_value=5),
    seed=st.integers(min_value=0, max_value=1_000_000),
    permutation_seed=st.integers(min_value=0, max_value=1_000_000),
)
def test_actions_in_same_lane_pairwise_conflict_or_transitively_conflict(
    n: int, num_locks: int, seed: int, permutation_seed: int
) -> None:
    """PRD US-003 line 310: for any two actions in the same lane, there
    exists a path of conflicts connecting them — i.e., a lane is a
    connected component of the conflict graph.

    Generates ``n`` LockedActions whose read/write lock sets are random
    subsets of a small pool of ``num_locks`` accounts. Builds the
    conflict graph externally via union-find using the public
    ``conflicts`` predicate, then asserts that two actions land in the
    same ``ParallelLane`` iff they share an external component id. The
    iff direction is the line-310 contract (same lane => transitively
    conflicting); the inverse direction (line 311) is also checked here
    as a stronger pin since both come for free from the equivalence.
    """
    import random as _random

    rng = _random.Random(seed)
    pool = [f"acct-{i}" for i in range(num_locks)]
    actions: list[LockedAction] = []
    for i in range(n):
        # Random non-empty subset of the pool split into read / write.
        # An action with empty write_locks is read-only — still useful
        # because read-write overlaps must conflict.
        reads: set[str] = set()
        writes: set[str] = set()
        for acct in pool:
            roll = rng.randrange(3)
            if roll == 0:
                reads.add(acct)
            elif roll == 1:
                writes.add(acct)
            # roll == 2 -> action does not touch this account
        actions.append(
            _locked_action_with_locks(
                agent_id=f"agent-{i}",
                read_locks=frozenset(reads),
                write_locks=frozenset(writes),
            )
        )

    perm_rng = _random.Random(permutation_seed)
    perm_rng.shuffle(actions)

    expected_components = _external_components(actions)
    lanes = PriorityScheduler().schedule(actions, slot=0)

    # Map each action's identity (by Python ``id``) back to its lane index.
    lane_of: dict[int, int] = {}
    for lane_idx, lane in enumerate(lanes):
        for la in lane.actions:
            lane_of[id(la)] = lane_idx

    # Total-action invariant: every input action lands in exactly one lane.
    assert len(lane_of) == n
    assert sum(len(lane.actions) for lane in lanes) == n

    # The line-310 contract (same lane => same external component) AND
    # its converse (same external component => same lane) — both come
    # from the equivalence ``lane partition == component partition``.
    for i in range(n):
        for j in range(i + 1, n):
            same_lane = lane_of[id(actions[i])] == lane_of[id(actions[j])]
            same_component = expected_components[i] == expected_components[j]
            assert same_lane == same_component, (
                f"lane/component mismatch at ({i}, {j}): "
                f"same_lane={same_lane}, same_component={same_component}, "
                f"action_i locks=(r={actions[i].read_locks}, w={actions[i].write_locks}), "
                f"action_j locks=(r={actions[j].read_locks}, w={actions[j].write_locks})"
            )


@settings(max_examples=200, deadline=None)
@given(
    n=st.integers(min_value=0, max_value=15),
    num_locks=st.integers(min_value=1, max_value=5),
    seed=st.integers(min_value=0, max_value=1_000_000),
    permutation_seed=st.integers(min_value=0, max_value=1_000_000),
)
def test_actions_in_different_lanes_pairwise_non_conflict_at_root(
    n: int, num_locks: int, seed: int, permutation_seed: int
) -> None:
    """PRD US-003 line 311: two actions in different lanes do not directly
    conflict — i.e., different lanes correspond to disjoint connected
    components of the conflict graph.

    The iff equivalence is already pinned by the line-310 test above, but
    the PRD lists this converse as a separately-named contract. A focused
    test gives a targeted failure message ("found a direct conflict
    between actions in different lanes") that points at the exact
    invariant a regression would break, instead of the broader
    "lane/component mismatch" surfaced by the line-310 assertion.

    Generates the same random read/write lock subsets over a small pool
    of accounts, then iterates every (i, j) pair where the scheduler
    placed action i and action j in DIFFERENT lanes and asserts
    ``conflicts(actions[i], actions[j]) is False``.
    """
    import random as _random

    rng = _random.Random(seed)
    pool = [f"acct-{i}" for i in range(num_locks)]
    actions: list[LockedAction] = []
    for i in range(n):
        reads: set[str] = set()
        writes: set[str] = set()
        for acct in pool:
            roll = rng.randrange(3)
            if roll == 0:
                reads.add(acct)
            elif roll == 1:
                writes.add(acct)
        actions.append(
            _locked_action_with_locks(
                agent_id=f"agent-{i}",
                read_locks=frozenset(reads),
                write_locks=frozenset(writes),
            )
        )

    perm_rng = _random.Random(permutation_seed)
    perm_rng.shuffle(actions)

    lanes = PriorityScheduler().schedule(actions, slot=0)

    lane_of: dict[int, int] = {}
    for lane_idx, lane in enumerate(lanes):
        for la in lane.actions:
            lane_of[id(la)] = lane_idx

    assert len(lane_of) == n

    for i in range(n):
        for j in range(i + 1, n):
            if lane_of[id(actions[i])] != lane_of[id(actions[j])]:
                assert not conflicts(actions[i], actions[j]), (
                    f"found a direct conflict between actions in different lanes at ({i}, {j}): "
                    f"action_i locks=(r={actions[i].read_locks}, w={actions[i].write_locks}), "
                    f"action_j locks=(r={actions[j].read_locks}, w={actions[j].write_locks})"
                )
