"""Canonical Solana program IDs used by replay and wallet integrations."""

from __future__ import annotations

SYSTEM_PROGRAM = "11111111111111111111111111111111"
COMPUTE_BUDGET_PROGRAM = "ComputeBudget111111111111111111111111111111"
MEMO_PROGRAM = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
MEMO_LEGACY_PROGRAM = "Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo"

TOKEN_PROGRAM = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
TOKEN_2022_PROGRAM = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

WHIRLPOOL_PROGRAM = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
RAYDIUM_AMM_V4_PROGRAM = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
METEORA_DLMM_PROGRAM = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"
KAMINO_LEND_PROGRAM = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
JUPITER_PERPS_PROGRAM = "PERPHjGBqRHArX4DySjwM6UJHiR3sWAatqfdBS2qQJu"
PYTH_PRICE_FEED_PROGRAM = "pythWSnswVUd12oZpeFP8e9CVaEqJg25g1Vtc2biRsT"
PYTH_SOLANA_RECEIVER_PROGRAM = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"

TOKEN_PROGRAM_IDS = frozenset((TOKEN_PROGRAM, TOKEN_2022_PROGRAM))
TRANSPARENT_REPLAY_PROGRAM_IDS = frozenset(
    (COMPUTE_BUDGET_PROGRAM, MEMO_PROGRAM, MEMO_LEGACY_PROGRAM)
)

__all__ = [
    "COMPUTE_BUDGET_PROGRAM",
    "JUPITER_PERPS_PROGRAM",
    "KAMINO_LEND_PROGRAM",
    "MEMO_LEGACY_PROGRAM",
    "MEMO_PROGRAM",
    "METEORA_DLMM_PROGRAM",
    "PYTH_PRICE_FEED_PROGRAM",
    "PYTH_SOLANA_RECEIVER_PROGRAM",
    "RAYDIUM_AMM_V4_PROGRAM",
    "SYSTEM_PROGRAM",
    "TOKEN_2022_PROGRAM",
    "TOKEN_PROGRAM",
    "TOKEN_PROGRAM_IDS",
    "TRANSPARENT_REPLAY_PROGRAM_IDS",
    "WHIRLPOOL_PROGRAM",
]
